version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"  
    env_file:
      - .env           
    volumes:
      - .:/app        
      - ./dev.db:/app/dev.db 
    command: npm run dev
